[package]
name = "penning-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
reqwest = "0.12.7"
self-replace = "1.5.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
